trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm i -g @angular/cli
    npm i -g npx
    npm i
  displayName: 'npm install'

- script: ng build --prod
  displayName: 'build'
